
const regularCats = {
  bagira: { name: "בגירה", image: "images/bagira.png", short: "פלאפית, קנאית, מלכת הבית שלא יוצאת לשום מקום.", lore: "בגירה אוהבת פינוקים, מתה על להיות על הידיים, נעימה ופלאפית בטירוף, שונאת חתולות, אוהבת זכרים, וקנאית מסריחה שלא יוצאת מהבית. היא נסיכת פנים עם לב של כרית וחוש בעלות של עורך דין.", tags: ["פינוקים", "ידיים עכשיו", "קנאית", "אנטי חוץ"] },
  sumsum: { name: "סומסום", image: "images/sumsum.png", short: "דוכס גרגרן, שמן, אוהב חתולות וליטופים, נווד בלתי נלאה.", lore: "סומסום הוא הדוכס הגרגרן של הממלכה: שמן, אפור, מאוהב בחטיפים, אוהב חתולות, אוהב ליטופים, ונווד אין־סופי. יש לו אנרגיה של מי שנעלם לשלושה רחובות וחוזר כי מישהו פתח טונה.", tags: ["גרגרן", "ליטופים", "נווד", "דוכס"] },
  chag: { name: "צ׳אג", image: "images/chag.png", short: "האמא הרעה של סינדרלה ושלטון ברזל על כל מי שנושם.", lore: "צ׳אג שולטת בבית ביד ברזל ובכף פרווה. אם משהו לא עובד בכוח — היא עובדת ביותר כוח. חייבת פינוקים רק לעצמה, מכפכפת את כולם, ושונאת זכרים בעקביות מעוררת השראה.", tags: ["דיקטטורית", "פינוקים שלי", "כפכופים", "אנטי זכרים"] },
  tomi: { name: "טומי", image: "images/tomi.png", short: "זקנה, פחדנית, מיללת הרבה, אבל תמיד חוזרת הביתה.", lore: "טומי היא גברת מבוגרת עם חרדות, מסעות קצרים, וקול שלא מפסיק. היא מטיילת, בורחת, נבהלת, ואז חוזרת כאילו כלום. בנוסף היא אוהבת ללוש בני אנוש כאילו הם בצק עם נשמה.", tags: ["זקנה עם סטייל", "פחדנית", "מייללת", "לישה"] },
  blue: { name: "בלו", image: "images/blue_akila.png", short: "אחד מצמד הטרור. רץ אחרי כפות רגליים ולא מכיר מנוחה.", lore: "בלו הוא אחד הילדים של בגירה: שטותניק, שובב, רודף אחרי כפות רגליים, שותה חלב, מטפס על הספה, ולא נח לרגע. הוא תינוק כאוס עם פרצוף תמים של שקרן מקצועי.", tags: ["גור טרור", "חלב", "כפות רגליים", "בלי ברקסים"] },
  akila: { name: "אקילה", image: "images/blue_akila.png", short: "האחות התאומה עם אותה אנרגיית פשע, רק עם עוד חוצפה בעיניים.", lore: "אקילה היא הילדה של בגירה ואחותו לפשע של בלו: שובבה, מטפסת, רצה אחרי כפות רגליים, שותה חלב, ולא יודעת מה זה לנוח. אם יש בלגן — כנראה היא חשבה עליו חצי דקה קודם.", tags: ["תאומה מסוכנת", "ספה זה הר", "חלב", "כאוס"] },
  gary: { name: "גרי", image: "images/gary.png", short: "אצילי, חכם, עדין, ואוהב בני אדם באופן מחשיד.", lore: "גרי הוא אציל, חכם, עדין, אוהב בני אדם, רץ מהר, ופורץ הביתה כשמתאפשר. יש לו וייב של גנב־ג׳נטלמן שחושב שכל בית הוא בעצם שלו אם רק פתחו רגע דלת.", tags: ["אצילי", "אוהב אנשים", "רץ מהר", "פורץ מכובד"] }
};
const silverCats = {
  kachulit: { name: "כחולית", image: "images/kachulit.png", short: "בין הראשונות, לרגע גם המועדפת, נשאר לה מקום חם בלב.", lore: "כחולית הייתה בין הראשונות ולרגע גם המועדפת. לצערה הגיעה למצב של עיוורון והייתה חצי גמורה במשך תקופה ארוכה. עדיין היה לה מקום חם בלב — ולא יותר מזה.", tags: ["OG כסופה", "מקום חם בלב", "מיתולוגית", "נדירה"] },
  poof: { name: "פוף", image: "images/poof.png", short: "רזה, ראש גדול, אשכים בלתי ניתנים להתעלמות, ופוזל באהבה.", lore: "פוף היה חתול רזה עם ראש גדול ואשכים שלא מתפספסים מרחוק. הוא קיבל איזה אירוע ופזל כל היום. הרבה שכל לא היה שם, אבל אכן מתוק ברמה מסוכנת.", tags: ["OG כסוף", "ראש גדול", "פוזל", "מתוק מדי"] }
};
const goldCards = {
  mitch: { name: "מיצ", image: "images/mitch.png", short: "השנייה בשושלת. קטנה, רזה, מלאכית, ומנוזלת באופן הירואי.", lore: "מיצ הייתה השנייה. היא ניסתה להמשיך את השושלת אך נפלה בקרב לאחר מאבק עיקש בצינון כרוני. קטנה, רזה, בוגרת, עם כנפיים של מלאך כי אגדות לא באמת הולכות לשום מקום.", tags: ["OG שנייה", "מלאכית", "צינון כרוני", "אגדה"] },
  ketem: { name: "כתם", image: "images/ketem.png", short: "הארנבת הלבנה. מסריחה, חופרת ברצפה, ותכלס פשוט שם.", lore: "כתם היא הארנבת הלבנה והשמנה של החבורה. היא תמיד מסריחה, תמיד חופרת ברצפה, ואין לה באמת תכלית ברורה. היא פשוט שם — ובאופן בלתי מוסבר זה הפך אותה לחשובה.", tags: ["ארנבת", "שמנה", "חופרת", "פשוט שם"] },
  chavrika: { name: "חבריקה", image: "images/chavrika.png", short: "ה־OG המיתולוגית. הראשונה. האלפא. זו שהתחילה הכל.", lore: "חבריקה היא החתולה המיתולוגית — הראשונה שהייתה שם, הוגת האבולוציה, והתחלת כל השושלת. היא מתה בשיבה טובה ולכן לא יוצאת בחידון. היא קלף זהב אלוהי, מושלם, קדוש, ויפה באופן לא סביר.", tags: ["OG", "מיתולוגית", "מלאך מושלם", "התחילה הכל"] },
  joy: { name: "ג׳וי", image: "images/joy.png", short: "האחת והיחידה. כל מילה מעבר לזה באמת מיותרת.", lore: "ג׳וי הייתה הכלבה של המשפחה. היא האחת והיחידה. אין צורך להרחיב, אין צורך להצדיק, אין צורך להסביר. זה קלף הסיום, האלוהים בפני עצמו, השלמות עטופה בפרווה.", tags: ["הכלבה", "אלוהות", "שלמות", "האחת והיחידה"] }
};
const hokeCard = { name: "הוק", image: "images/hoke.png", short: "השרקן האהוב, חברו הטוב של ג׳וי, נסיך שמתחבא.", lore: "הוק היה השרקן האהוב. הוא אהב להתחבא והיה חברו הטוב של ג׳וי. שרקן נסיך, קטן בגודל, ענק במעמד, ומפעיל רשמי של משחק ניחוש השיר.", tags: ["שרקן נסיך", "מתחבא", "חבר של ג׳וי", "משחק השיר"] };
const quizQuestions = [
  { q: "את/ה מקבל/ת בדואר כפכף בודד עם פתק שכתוב עליו ‘הוא יודע’. מה עושים?", a: [ { t: "שומר/ת אותו למקרה שיהיה משפט", s: ["bagira", "tomi"], og: ["kachulit"] }, { t: "בודק/ת אם הוא אכיל כי לא פוסלים חוויות", s: ["sumsum", "gary"] }, { t: "מכריז/ה עליו כראש ממשלה זמני", s: ["chag", "akila"], og: ["poof"] }, { t: "רץ/ה אחריו במסדרון כי הוא התחיל", s: ["blue", "akila"] } ] },
  { q: "באמצע חתונה מישהו מביא לך מלפפון עם כובע. מה התגובה הסבירה?", a: [ { t: "אומר/ת לו ‘סוף סוף מישהו פה לבוש בהתאם’", s: ["gary", "bagira"] }, { t: "שואל/ת אם יש גם טחינה כי זה מתפתח", s: ["sumsum", "tomi"] }, { t: "ממנה אותו לאחראי משמעת ברחבה", s: ["chag", "akila"] }, { t: "נותן/ת לו שם, מאבד/ת אותו, ובוכה קלות", s: ["blue", "akila"], og: ["kachulit"] } ] },
  { q: "בחר/י סיבה הגיונית להיכנס לארון ולצאת משם עם תעודת זהות אחרת:", a: [ { t: "הייתה שם אנרגיה לא סגורה", s: ["bagira", "tomi"] }, { t: "חשבתי שיש שם ביסלי, יצאתי עם עבר", s: ["sumsum", "gary"] }, { t: "היה צריך לארגן מחדש את השלטון הפנימי", s: ["chag", "akila"], og: ["poof"] }, { t: "נכנסתי אחרי שרוך. אין לי עוד פרטים", s: ["blue", "akila"] } ] },
  { q: "אם כיסא היה שולח לך הודעה ‘ערה?’ מה היית עונה?", a: [ { t: "‘תלוי מי שואל ומה גובה המשענת’", s: ["bagira", "gary"], og: ["kachulit"] }, { t: "‘יש לך חטיפים או שאתה סתם רהיט?’", s: ["sumsum", "tomi"] }, { t: "‘קודם תתנצל על כל הפינות שפגעו בי’", s: ["chag", "akila"] }, { t: "‘אני כבר בדרך לרדוף אחרי הרגליים שלך’", s: ["blue", "akila"] } ] },
  { q: "איזה פריט הכי מתאים לשים במוזיאון של החלטות גרועות?", a: [ { t: "מראה שאומרת ‘אל תתחיל/י איתי היום’", s: ["bagira", "chag"] }, { t: "פיתה חתומה על ידי מי שנשבע שזה הביס האחרון", s: ["sumsum", "gary"] }, { t: "קומקום שצעק פעם אחת ומאז כולם בטראומה", s: ["tomi", "bagira"], og: ["kachulit"] }, { t: "גרב שהוגדרה כחשודה ונרדפה עד המטבח", s: ["blue", "akila"], og: ["poof"] } ] },
  { q: "היקום נותן לך שלט רחוק אבל יש בו רק כפתור אחד. מה כתוב עליו?", a: [ { t: "‘תרים אותי’", s: ["bagira", "gary"] }, { t: "‘עוד משהו קטן’", s: ["sumsum", "tomi"] }, { t: "‘יותר כוח’", s: ["chag", "akila"] }, { t: "‘רוץ בלי סיבה’", s: ["blue", "akila"], og: ["poof"] } ] },
  { q: "באמצע מבחן מופיעה לפניך קערת מרק עם שפם. מה מסמנים?", a: [ { t: "ג׳ — כי המרק נראה בטוח בעצמו", s: ["gary", "bagira"] }, { t: "את המרק, עם לחם בצד", s: ["sumsum", "tomi"] }, { t: "לא מסמנים. הופכים את השולחן בשם הצדק", s: ["chag", "akila"] }, { t: "שואלים אם השפם פנוי למשחק", s: ["blue", "akila"], og: ["kachulit"] } ] }
];
const regularOrder = ["bagira","sumsum","chag","tomi","blue","akila","gary"];
const silverOrder = ["kachulit","poof"];
const goldOrder = ["mitch","ketem","chavrika","joy"];
const unlockSequence = ["mitch", "ketem", "hoke", "chavrika"];
const storage = window.sessionStorage;
const qs = s => document.querySelector(s);
const qsa = s => [...document.querySelectorAll(s)];
const questionsWrap = qs('#questions');
const progressBar = qs('#progressBar');
const toast = qs('#toast');
let secretDelayUntil = Date.now();
function scheduleNextSecret() { secretDelayUntil = Date.now() + 10000; setTimeout(updateSecretVisibility, 10050); }
function canShowSecret() { return Date.now() >= secretDelayUntil; }
function getUnlocks() { return JSON.parse(storage.getItem('catGoldUnlocks') || '{}'); }
function setUnlocks(obj) { storage.setItem('catGoldUnlocks', JSON.stringify(obj)); }
function getStats() { return JSON.parse(localStorage.getItem('catQuizStats') || '{}'); }
function setStats(obj) { localStorage.setItem('catQuizStats', JSON.stringify(obj)); }
function showToast(text) { toast.textContent = text; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2200); }
function buildQuiz() { questionsWrap.innerHTML = quizQuestions.map((item,i)=>`<section class="question"><h4>${i+1}. ${item.q}</h4><div class="options">${item.a.map((ans,j)=>`<label class="option"><input type="radio" name="q${i}" value="${j}" required><span>${ans.t}</span></label>`).join('')}</div></section>`).join(''); }
function updateProgress() { const count = quizQuestions.filter((_,i)=>qs(`input[name="q${i}"]:checked`)).length; progressBar.style.width = `${count / quizQuestions.length * 100}%`; }
function computeResult(formData) { const scores = Object.fromEntries(regularOrder.map(k=>[k,0])); const ogScores = Object.fromEntries(silverOrder.map(k=>[k,0])); quizQuestions.forEach((item,i)=>{ const picked=Number(formData.get(`q${i}`)); const ans=item.a[picked]; if(!ans) return; ans.s.forEach(k=>scores[k]+=1); (ans.og||[]).forEach(k=>ogScores[k]+=1); }); const ogMax=Math.max(...Object.values(ogScores),0); const ogCandidates=Object.entries(ogScores).filter(([,v])=>v===ogMax&&v>0).map(([k])=>k); const rareChance=ogMax>=2?0.22:ogMax===1?0.08:0; if(ogCandidates.length&&Math.random()<rareChance) return ogCandidates[Math.floor(Math.random()*ogCandidates.length)]; const highest=Math.max(...Object.values(scores)); const winners=Object.entries(scores).filter(([,v])=>v===highest).map(([k])=>k); return winners[Math.floor(Math.random()*winners.length)]; }
function showResult(key) { const cat = regularCats[key] || silverCats[key]; qs('#resultImage').src=cat.image; qs('#resultName').textContent=cat.name; qs('#resultDesc').textContent=cat.lore; qs('#resultTags').innerHTML=cat.tags.map(t=>`<span class="tag">${t}</span>`).join(''); qs('#resultCard').classList.remove('hidden'); qs('#resultCard').scrollIntoView({behavior:'smooth',block:'center'}); qs('#openResultCard').onclick=()=>openCardModal(cat, silverCats[key]?'תוצאת OG נדירה':'תוצאת חידון'); }
function saveStat(key) { const stats=getStats(); stats[key]=(stats[key]||0)+1; setStats(stats); renderStats(); }
function renderRegular() { qs('#regularGrid').innerHTML=regularOrder.map(key=>{ const cat=regularCats[key]; return `<article class="card-shell reveal regular-card" data-key="${key}"><img src="${cat.image}" alt="${cat.name}"><div class="card-info"><h4>${cat.name}</h4><p>${cat.short}</p></div></article>`; }).join(''); qsa('.regular-card').forEach(el=>el.addEventListener('click',()=>openCardModal(regularCats[el.dataset.key],'קלף רגיל'))); }
function renderSilver() { const target=qs('#silverGrid'); if(!target) return; target.innerHTML=silverOrder.map(key=>{ const cat=silverCats[key]; return `<article class="card-shell reveal silver-card" data-key="${key}"><img src="${cat.image}" alt="${cat.name}"><div class="card-info"><h4>${cat.name}</h4><p>${cat.short}</p></div></article>`; }).join(''); qsa('.silver-card').forEach(el=>el.addEventListener('click',()=>openCardModal(silverCats[el.dataset.key],'קלף OG כסוף'))); }
function lockedCardMarkup(){ return `<article class="card-shell gold-card locked generic-locked"><div><div class="lock-badge">🔒</div><h4>קלף זהב נעול</h4></div></article>`; }
function renderGold(){ const unlocks=getUnlocks(); qs('#goldGrid').innerHTML=goldOrder.map(key=>{ const card=goldCards[key]; const unlocked=!!unlocks[key]; if(!unlocked) return lockedCardMarkup(); return `<article class="card-shell gold-card unlocked" data-key="${key}"><img src="${card.image}" alt="${card.name}"><div class="card-info"><h4>${card.name}</h4><p>${card.short}</p></div></article>`; }).join(''); qsa('.gold-card.unlocked').forEach(el=>el.addEventListener('click',()=>openCardModal(goldCards[el.dataset.key],'קלף זהב'))); updateSecretVisibility(); }
function openCardModal(card,type='קלף'){ qs('#modalImage').src=card.image; qs('#modalName').textContent=card.name; qs('#modalLore').textContent=card.lore; qs('#modalType').textContent=type; qs('#modalTags').innerHTML=(card.tags||[]).map(t=>`<span class="tag">${t}</span>`).join(''); qs('#cardModal').classList.remove('hidden'); }
function closeModal(){ qs('#cardModal').classList.add('hidden'); }
function unlockGold(key){ const unlocks=getUnlocks(); if(key==='hoke'){ unlocks.hoke=true; setUnlocks(unlocks); showHokeGame(); openCardModal(hokeCard,'הוק הגיע!'); showToast('הוק הופיע. עכשיו תנחשו את השיר.'); scheduleNextSecret(); updateSecretVisibility(); return; } if(unlocks[key]){ openCardModal(goldCards[key],'קלף זהב'); return; } unlocks[key]=true; setUnlocks(unlocks); renderGold(); openCardModal(goldCards[key],'נאסף! קלף זהב'); showToast(`נאסף קלף הזהב: ${goldCards[key].name}`); scheduleNextSecret(); updateSecretVisibility(); }
function nextAngelCard(){ const unlocks=getUnlocks(); return unlockSequence.find(key=>!unlocks[key])||null; }
function updateSecretVisibility(){ const unlocks=getUnlocks(); const next=nextAngelCard(); const canShow=canShowSecret(); qs('#secretAngel').classList.toggle('hidden',!next||next==='hoke'||!canShow); qs('#secretHoke').classList.toggle('hidden',next!=='hoke'||!canShow); const specialDone=unlockSequence.every(key=>!!unlocks[key]); qs('#secretJoy').classList.toggle('hidden',!specialDone||!!unlocks.joy||!canShow); renderHokeState(); }
function showHokeGame(){ const card=qs('#hokeGameCard'); const locked=qs('#hokeLockedCard'); if(card) card.classList.remove('hidden'); if(locked) locked.classList.add('hidden'); }
function renderHokeState(){ const unlocks=getUnlocks(); const card=qs('#hokeGameCard'); const locked=qs('#hokeLockedCard'); if(!card||!locked) return; if(unlocks.hoke){ card.classList.remove('hidden'); locked.classList.add('hidden'); } else { card.classList.add('hidden'); locked.classList.remove('hidden'); } }
function normalizeAnswer(value){ return (value||'').toLowerCase().replace(/[״"׳']/g,'').replace(/\s+/g,'').trim(); }
function checkHokeAnswer(){ const answer=normalizeAnswer(qs('#songGuess')?.value); const correct=normalizeAnswer('הרקדן האוטומטי'); const feedback=qs('#songFeedback'); if(!feedback) return; if(answer===correct||answer.includes(correct)){ feedback.textContent='יא מלך יצאת רקדן תעשה סיבוב ותעוף מכאן.'; feedback.className='song-feedback success'; const unlocks=getUnlocks(); unlocks.hokeSolved=true; setUnlocks(unlocks); } else { feedback.textContent='לא. הוק הסתכל עלייך דרך הפוני של השרקנים. נסי שוב.'; feedback.className='song-feedback error'; } }
function renderStats(){ const stats=getStats(); const allKeys=[...regularOrder,...silverOrder]; const values=allKeys.map(k=>stats[k]||0); const max=Math.max(...values,1); qs('#statsCard').innerHTML=allKeys.map(key=>{ const cat=regularCats[key]||silverCats[key]; const count=stats[key]||0; const width=count/max*100; return `<div class="stat-row"><strong>${cat.name}</strong><div class="stat-track"><div class="stat-fill" style="width:${width}%"></div></div><span>${count}</span></div>`; }).join('')+`<div class="quiz-actions compact"><button class="btn secondary" id="resetStats">איפוס סטטיסטיקות</button></div>`; qs('#resetStats').addEventListener('click',()=>{ localStorage.removeItem('catQuizStats'); renderStats(); showToast('הסטטיסטיקות התאדו. שום דבר לא קרה פה.'); }); }
function pickDaily(){ const key=regularOrder[Math.floor(Math.random()*regularOrder.length)]; const cat=regularCats[key]; qs('#dailyImage').src=cat.image; qs('#dailyName').textContent=cat.name; qs('#dailyText').textContent=cat.short; }
function setupNav(){ qs('#menuBtn').addEventListener('click',()=>qs('#nav').classList.toggle('open')); qsa('.nav a').forEach(a=>a.addEventListener('click',()=>qs('#nav').classList.remove('open'))); const sections=qsa('main section[id]'); const links=qsa('.nav a'); const obs=new IntersectionObserver(entries=>{ entries.forEach(entry=>{ if(!entry.isIntersecting)return; links.forEach(l=>l.classList.toggle('active',l.getAttribute('href')===`#${entry.target.id}`)); }); },{threshold:.35}); sections.forEach(sec=>obs.observe(sec)); }
function setupReveal(){ const obs=new IntersectionObserver(entries=>{ entries.forEach(entry=>{ if(entry.isIntersecting) entry.target.classList.add('visible'); }); },{threshold:.15}); qsa('.reveal').forEach(el=>obs.observe(el)); }
buildQuiz(); renderRegular(); renderSilver(); renderGold(); renderStats(); pickDaily(); renderHokeState(); setupNav(); setupReveal();
questionsWrap.addEventListener('change',updateProgress); qs('#dailyBtn').addEventListener('click',pickDaily); qs('#quizForm').addEventListener('submit',e=>{ e.preventDefault(); const winner=computeResult(new FormData(e.currentTarget)); saveStat(winner); showResult(winner); }); qs('#resetQuiz').addEventListener('click',()=>{ qs('#quizForm').reset(); progressBar.style.width='0'; qs('#resultCard').classList.add('hidden'); }); qs('#copyResult').addEventListener('click',async()=>{ const text=`יצא לי ${qs('#resultName').textContent} באתר החתולים. לא יודעת אם להיעלב או להסכים.`; try{ await navigator.clipboard.writeText(text); showToast('האבחון הועתק. עכשיו להפיץ ולברוח.'); }catch{ showToast(text); } }); qs('#secretAngel').addEventListener('click',()=>{ const next=nextAngelCard(); if(next) unlockGold(next); }); qs('#secretHoke').addEventListener('click',()=>unlockGold('hoke')); qs('#secretJoy').addEventListener('click',()=>unlockGold('joy')); qs('#submitSongGuess')?.addEventListener('click',checkHokeAnswer); qs('#openHokeCard')?.addEventListener('click',()=>openCardModal(hokeCard,'קלף הוק')); qs('#closeModal').addEventListener('click',closeModal); qs('#cardModal').addEventListener('click',e=>{ if(e.target.dataset.close) closeModal(); }); document.addEventListener('keydown',e=>{ if(e.key==='Escape') closeModal(); });
